apiVersion: 1
datasources:
  - name: SmartGrid
    uid: smartgrid
    type: grafana-postgresql-datasource
    url: host.docker.internal:5432
    user: postgres
    isDefault: true
    jsonData:
      database: smart_grid
      sslmode: disable
      timescaledb: true
      postgresVersion: 1700
      maxOpenConns: 10
    secureJsonData:
      password: ${PGPASSWORD}